import Head from "next/head";
import { useState } from "react";
import Navbar from "@/components/navbar/Navbar";
import Hero from "@/components/hero/Hero";
import Skills from "@/components/skills/Skills";
import Portfolio from "@/components/portfolio/Portfolio";
import Contact from "@/components/contact/Contact";
import Nav from "@/components/nav/Nav";
import Footer from "@/components/footer/Footer";

export default function Home() {
  const [darkmode, setDarkMode] = useState("false");
  return (
    <>
      <div className={darkmode ? "" : "dark"}>
        <Head>
          <title>JASS || Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/js.ico" />
        </Head>
        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <Navbar darkMode={darkmode} setDarkMode={setDarkMode} />
          <Hero />
          <Skills />
          <Portfolio />
          <Contact />
          <Footer />
          <Nav />
        </main>
      </div>
    </>
  );
}
