import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import Hero from "@/components/hero/Hero";
import Skills from "@/components/skills/Skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>JASS || Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 mb-20">
        <Navbar />
        <Hero />
        <Skills />
      </main>
    </>
  );
}
